const d = window.CV;
const variant = document.body.dataset.design;
const esc = x => String(x).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const heading = (s) => `<h2>${s}</h2>`;
const contact = () => `<div class="contact"><a href="mailto:${esc(d.email)}">${esc(d.email)}</a><a href="tel:+33681803409">${esc(d.phone)}</a></div>`;
const portrait = () => `<img class="portrait" src="assets/laura-portrait.png" alt="Laura Leiboff">`;
const intro = () => `<p class="intro">${esc(d.intro)}</p>`;
const stat = () => `<p class="travel-note">Travelled to ${esc(d.countries)} countries</p>`;
const languages = () => `<section class="languages">${heading('Languages')}<dl>${d.languages.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl></section>`;
const strengths = () => `<section class="strengths">${heading('What I bring')}<ul>${d.strengths.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section>`;
const interests = () => `<section class="interests">${heading('Beyond the itinerary')}<ul>${d.interests.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section>`;
const education = () => `<section class="education">${heading('Education')}<div>${d.education.map(([title,org,year])=>`<p><strong>${esc(title)}</strong><span>${esc(org)} · ${esc(year)}</span></p>`).join('')}</div></section>`;
const jobs = () => `<section class="experience">${heading('Selected experience')}<div class="jobs">${d.jobs.map((j,i)=>`<article class="job"><div class="job-date"><span class="job-number">0${i+1}</span>${esc(j.date)}</div><div class="job-copy"><h3>${esc(j.title)}</h3><p class="company">${esc(j.company)} <span>· ${esc(j.place)}</span></p><p class="description">${esc(j.description)}</p></div></article>`).join('')}</div></section>`;
const name = () => `<h1><span>${esc(d.firstName)}</span> <span>${esc(d.lastName)}</span></h1>`;
const title = () => `<p class="role">${esc(d.title)}</p>`;
const footer = () => `<footer><span>Laura Leiboff / Curriculum vitae</span></footer>`;
const globe = `<svg class="globe" viewBox="0 0 240 240" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="1"><circle cx="120" cy="120" r="108"/><ellipse cx="120" cy="120" rx="65" ry="108"/><ellipse cx="120" cy="120" rx="26" ry="108"/><ellipse cx="120" cy="120" rx="108" ry="40"/><ellipse cx="120" cy="120" rx="108" ry="78"/><path d="M12 120h216M120 12v216"/></g></svg>`;
const route = `<svg class="route" viewBox="0 0 180 180" fill="none" aria-hidden="true"><path d="M30 148C-14 72 160 153 136 43" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-dasharray="4 8"/><circle cx="30" cy="148" r="8" fill="currentColor"/><path d="M136 17c-15 0-24 10-24 24 0 18 24 41 24 41s24-23 24-41c0-14-9-24-24-24Z" fill="currentColor"/><circle cx="136" cy="41" r="8" fill="var(--soft)"/></svg>`;
let html;
if(variant==='editorial') html = `<header><div class="eyebrow">Tour leader / Expeditions / Ski instructor</div>${name()}${portrait()}${contact()}</header><div class="main-grid"><aside>${languages()}${strengths()}${interests()}${stat()}</aside><main>${intro()}${jobs()}${education()}</main></div>${footer()}`;
if(variant==='atlas') html = `<header><div class="eyebrow">People. Places. Possibilities.</div>${name()}${title()}${contact()}${globe}</header><main>${intro()}${stat()}${jobs()}<div class="bottom-grid">${education()}${languages()}</div></main>${footer()}`;
if(variant==='field') html = `<aside>${portrait()}${contact()}${languages()}${interests()}${stat()}<div class="sidebar-signoff">Curious by nature.</div></aside><main><header>${name()}${title()}</header>${intro()}${jobs()}${education()}</main>${footer()}`;
if(variant==='studio') html = `<header><div class="eyebrow">Tour leader / Expeditions / Ski instructor</div>${name()}${contact()}${route}</header><div class="intro-grid"><div class="intro-card">${heading('Up mountains, around the world')}${intro()}${stat()}</div></div><main>${jobs()}<div class="bottom-grid">${languages()}${education()}</div></main>${footer()}`;
document.querySelector('.sheet').innerHTML=html;
document.querySelector('[data-print]').addEventListener('click',()=>window.print());
